version: '3.4'
networks:
  travix-network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/16

services:
  crazyair.data.mysql:
    build:
      context: ./backend/crazyair
      dockerfile: Crazyair.Mysql.Dockerfile
    ports:
      - '3308:3306'
    networks:
      travix-network:
        ipv4_address: 10.10.10.102
    security_opt:
      - seccomp:unconfined
    restart: always

  toughjet.data.mysql:
    build:
      context: ./backend/toughjet
      dockerfile: ToughJet.Mysql.Dockerfile
    ports:
      - '3307:3306'
    networks:
      travix-network:
        ipv4_address: 10.10.10.104
    security_opt:
      - seccomp:unconfined
    restart: always

  crazyair.api:
    build:
      context: ./backend/crazyair
      dockerfile: Crazyair.Api.Dockerfile
    ports:
      - '8088:8088'
    networks:
      travix-network:
        ipv4_address: 10.10.10.103
    depends_on:
      - crazyair.data.mysql
    restart: always

  toughjet.api:
    build:
      context: ./backend/toughjet
      dockerfile: ToughJet.Api.Dockerfile
    ports:
      - '8090:8090'
    networks:
      travix-network:
        ipv4_address: 10.10.10.105
    depends_on:
      - toughjet.data.mysql
    restart: always
